using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace DigiCreatures
{
    public class CreatureSemanticTarget : MonoBehaviour
    {
        public string targetId = "semantic_target";
        public string displayName = "语义目标";
        [TextArea] public string description = "场景中一个值得智能体注意的目标。";
        public string semanticTags = "neutral";
        public CreatureNavigationKind navigationKind = CreatureNavigationKind.Walkable;
        [Range(0, 5)] public int dangerLevel;
        public int interestWeight = 1;
        public float approachRadius = 3f;
        public List<CreatureLocationMarker> linkedMarkers = new List<CreatureLocationMarker>();
        public bool isAutoGenerated = true;
        public int selectedCount;
        [TextArea] public string lastInterestReason;

        public string ToPromptLine(Transform creature)
        {
            float distance = creature == null ? 0f : Vector3.Distance(creature.position, transform.position);
            string markerIds = linkedMarkers == null
                ? string.Empty
                : string.Join(",", linkedMarkers.Where(marker => marker != null).Select(marker => marker.id));

            return $"{targetId}: {displayName} | kind={navigationKind} | tags={semanticTags} | interestWeight={Mathf.Max(1, interestWeight)} | danger={dangerLevel} | distance={distance:0.0} | approachMarkers={markerIds} | {description}";
        }

        public CreatureLocationMarker FirstReachableMarker()
        {
            if (linkedMarkers == null)
            {
                return null;
            }

            return linkedMarkers.FirstOrDefault(marker => marker != null);
        }

        public void RecordSelection(string reason)
        {
            selectedCount++;
            lastInterestReason = string.IsNullOrWhiteSpace(reason) ? "LLM 选择了这个目标。" : reason;
        }

        private void OnValidate()
        {
            if (string.IsNullOrWhiteSpace(targetId))
            {
                targetId = MakeId(gameObject.name);
            }

            if (string.IsNullOrWhiteSpace(displayName))
            {
                displayName = gameObject.name;
            }
        }

        private void OnDrawGizmosSelected()
        {
            Gizmos.color = NavigationColor(navigationKind);
            Gizmos.DrawWireSphere(transform.position, Mathf.Max(0.25f, approachRadius));
        }

        public static string MakeId(string source)
        {
            string value = string.IsNullOrWhiteSpace(source) ? "semantic_target" : source.Trim().ToLowerInvariant();
            char[] chars = value.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
            value = new string(chars).Trim('_');
            while (value.Contains("__", StringComparison.Ordinal))
            {
                value = value.Replace("__", "_");
            }

            return string.IsNullOrWhiteSpace(value) ? "semantic_target" : value;
        }

        private static Color NavigationColor(CreatureNavigationKind kind)
        {
            switch (kind)
            {
                case CreatureNavigationKind.Climbable:
                    return new Color(0.35f, 0.85f, 1f, 0.8f);
                case CreatureNavigationKind.Blocked:
                    return new Color(1f, 0.25f, 0.25f, 0.8f);
                case CreatureNavigationKind.JumpArea:
                    return new Color(1f, 0.85f, 0.2f, 0.8f);
                case CreatureNavigationKind.Platform:
                    return new Color(0.35f, 1f, 0.5f, 0.8f);
                case CreatureNavigationKind.InteractOnly:
                    return new Color(1f, 0.55f, 1f, 0.8f);
                default:
                    return new Color(0.2f, 0.8f, 1f, 0.8f);
            }
        }
    }

    public enum CreatureNavigationKind
    {
        Walkable,
        Climbable,
        Blocked,
        JumpArea,
        Platform,
        InteractOnly
    }
}
