using DigiCreatures;
using UnityEditor;
using UnityEngine;
using UnityEngine.AI;

namespace DigiCreaturesEditor
{
    [CustomEditor(typeof(CreatureSemanticTarget))]
    public sealed class CreatureSemanticTargetEditor : Editor
    {
        private bool showBackend;
        private bool showRuntime = true;

        public override void OnInspectorGUI()
        {
            serializedObject.Update();

            EditorGUILayout.HelpBox("开发者主要填写显示名称、描述、标签和导航类型；目标 ID、关联移动点这类字段主要给 LLM 和导航后端使用。", MessageType.Info);
            EditorGUILayout.PropertyField(serializedObject.FindProperty("displayName"), new GUIContent("显示名称", "展示给 LLM 和 Inspector 的中文名称。"));
            EditorGUILayout.PropertyField(serializedObject.FindProperty("description"), new GUIContent("兴趣描述", "描述这个物体为什么值得观察、接近或互动。"));
            EditorGUILayout.PropertyField(serializedObject.FindProperty("semanticTags"), new GUIContent("语义标签", "逗号分隔。用于提示 LLM 这个物体的类别和氛围。"));
            EditorGUILayout.PropertyField(serializedObject.FindProperty("navigationKind"), new GUIContent("导航类型", "对象语义层：可行走、可攀爬、阻挡、跳跃区域、平台或仅互动。"));
            EditorGUILayout.PropertyField(serializedObject.FindProperty("dangerLevel"), new GUIContent("危险等级", "0 表示安全，数字越高越应该谨慎靠近。"));
            EditorGUILayout.PropertyField(serializedObject.FindProperty("interestWeight"), new GUIContent("兴趣权重", "数值越高，扫描和 prompt 中越优先。"));
            EditorGUILayout.PropertyField(serializedObject.FindProperty("approachRadius"), new GUIContent("接近半径", "自动生成可达点时用于搜索附近 NavMesh 的半径。"));

            EditorGUILayout.Space(8f);
            showBackend = EditorGUILayout.Foldout(showBackend, new GUIContent("高级/后端", "这些字段会进入 prompt 或用于导航解析，通常由场景扫描自动维护。"), true);
            if (showBackend)
            {
                using (new EditorGUI.IndentLevelScope())
                {
                    EditorGUILayout.PropertyField(serializedObject.FindProperty("targetId"), new GUIContent("目标 ID", "LLM 使用这个 targetId 表达自己对哪个场景物体感兴趣。"));
                    EditorGUILayout.PropertyField(serializedObject.FindProperty("linkedMarkers"), new GUIContent("关联移动点", "LLM 选择这个目标后，系统优先使用这些可达点移动。"), true);
                    EditorGUILayout.PropertyField(serializedObject.FindProperty("isAutoGenerated"), new GUIContent("自动生成", "开启时下一次场景语义扫描可能更新该组件的描述和标签；关闭则作为手动标注保留。"));
                }
            }

            showRuntime = EditorGUILayout.Foldout(showRuntime, new GUIContent("运行时统计", "播放模式中由 LLM 选择时更新。"), true);
            if (showRuntime)
            {
                using (new EditorGUI.DisabledScope(true))
                using (new EditorGUI.IndentLevelScope())
                {
                    EditorGUILayout.PropertyField(serializedObject.FindProperty("selectedCount"), new GUIContent("被选择次数"));
                    EditorGUILayout.PropertyField(serializedObject.FindProperty("lastInterestReason"), new GUIContent("最近兴趣理由"));
                    EditorGUILayout.LabelField(new GUIContent("当前位置 NavMesh", "采样该对象附近的 NavMesh 区域。"), new GUIContent(SampleArea((CreatureSemanticTarget)target)));
                }
            }

            using (new EditorGUILayout.HorizontalScope())
            {
                using (new EditorGUI.DisabledScope(Application.isPlaying))
                {
                    if (GUILayout.Button(new GUIContent("重新扫描场景语义", "扫描场景对象并生成/更新语义目标和可达点。")))
                    {
                        CreatureSemanticSceneUtility.ScanAndGenerateTargets(true);
                    }
                }

                if (GUILayout.Button(new GUIContent("验证可达性", "检查当前语义目标关联的移动点是否落在 NavMesh 上。")))
                {
                    CreatureSemanticSceneUtility.ValidateReachability(true);
                }
            }

            serializedObject.ApplyModifiedProperties();
        }

        private static string SampleArea(CreatureSemanticTarget target)
        {
            if (target == null ||
                !NavMesh.SamplePosition(target.transform.position, out NavMeshHit hit, Mathf.Max(1f, target.approachRadius), NavMesh.AllAreas))
            {
                return "附近未采样到 NavMesh";
            }

            for (int i = 0; i < 32; i++)
            {
                if ((hit.mask & (1 << i)) == 0)
                {
                    continue;
                }

                string[] names = NavMesh.GetAreaNames();
                string areaName = i < names.Length ? names[i] : string.Empty;
                if (!string.IsNullOrWhiteSpace(areaName))
                {
                    return areaName;
                }
            }

            return "Unknown";
        }
    }
}
