using System;
using System.Collections.Generic;
using System.Linq;
using DigiCreatures;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.AI;

namespace DigiCreaturesEditor
{
    public static class CreatureSemanticSceneUtility
    {
        private const int MaxAutoTargets = 18;

        [MenuItem("数字生物/高级设置/场景语义/扫描并生成目标")]
        public static void ScanAndGenerateTargetsMenu()
        {
            ScanAndGenerateTargets(true);
        }

        [MenuItem("数字生物/高级设置/场景语义/验证可达性")]
        public static void ValidateReachabilityMenu()
        {
            string report = ValidateReachability(true);
            Debug.Log("场景语义可达性报告：\n" + report);
        }

        public static string ScanAndGenerateTargets(bool showDialog)
        {
            List<string> report = new List<string>();
            if (Application.isPlaying)
            {
                string playing = "播放模式中不修改场景语义。请退出播放模式后再扫描。";
                if (showDialog)
                {
                    EditorUtility.DisplayDialog("场景语义扫描", playing, "确定");
                }

                return playing;
            }

            List<SemanticCandidate> candidates = CollectCandidates();
            HashSet<GameObject> candidateObjects = new HashSet<GameObject>(candidates.Select(candidate => candidate.GameObject));
            int removedTargets = CleanupStaleAutoTargets(candidateObjects);

            HashSet<string> usedIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (CreatureSemanticTarget existing in CreatureObjectFinder.FindObjectsByType<CreatureSemanticTarget>(true))
            {
                if (!string.IsNullOrWhiteSpace(existing.targetId))
                {
                    usedIds.Add(existing.targetId);
                }
            }

            int createdTargets = 0;
            int updatedTargets = 0;
            int markerCount = 0;
            int virtualTargets = 0;

            foreach (SemanticCandidate candidate in candidates.Take(MaxAutoTargets))
            {
                CreatureSemanticTarget target = candidate.GameObject.GetComponent<CreatureSemanticTarget>();
                bool created = false;
                if (target == null)
                {
                    target = Undo.AddComponent<CreatureSemanticTarget>(candidate.GameObject);
                    created = true;
                    createdTargets++;
                }

                if (created || target.isAutoGenerated)
                {
                    ConfigureTarget(target, candidate, usedIds, created);
                    updatedTargets++;
                }

                markerCount += EnsureMarkersForTarget(target, candidate.Bounds);
            }

            virtualTargets += EnsureBoundaryTargets(candidates, usedIds, ref markerCount);

            foreach (CreatureSemanticTarget target in CreatureObjectFinder.FindObjectsByType<CreatureSemanticTarget>(true))
            {
                if (target != null)
                {
                    markerCount += EnsureMarkersForTarget(target, CalculateBounds(target.gameObject));
                }
            }

            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
            report.Add($"语义扫描完成：候选对象 {candidates.Count} 个，新建目标 {createdTargets} 个，更新目标 {updatedTargets} 个，边界语义 {virtualTargets} 个，移除旧自动目标 {removedTargets} 个，确认/生成移动点 {markerCount} 个。");
            report.Add("对象语义和 NavMesh 双层信息已经准备好：LLM 会先选择 targetId，再选择 approachPointId/destinationId。");

            string validation = ValidateReachability(false);
            if (!string.IsNullOrWhiteSpace(validation))
            {
                report.Add(validation);
            }

            string message = string.Join("\n", report);
            Debug.Log("场景语义扫描报告：\n" + message);
            if (showDialog)
            {
                EditorUtility.DisplayDialog("场景语义扫描", message, "确定");
            }

            return message;
        }

        public static string ValidateReachability(bool showDialog)
        {
            List<string> report = new List<string>();
            CreatureSemanticTarget[] targets = CreatureObjectFinder.FindObjectsByType<CreatureSemanticTarget>(true);
            CreatureLocationMarker[] markers = CreatureObjectFinder.FindObjectsByType<CreatureLocationMarker>(true);

            int reachableMarkers = 0;
            int unreachableMarkers = 0;
            foreach (CreatureLocationMarker marker in markers)
            {
                if (marker == null)
                {
                    continue;
                }

                if (NavMesh.SamplePosition(marker.transform.position, out NavMeshHit hit, 1.5f, NavMesh.AllAreas))
                {
                    reachableMarkers++;
                    marker.navAreaName = AreaMaskToName(hit.mask);
                    EditorUtility.SetDirty(marker);
                }
                else
                {
                    unreachableMarkers++;
                }
            }

            report.Add($"可达性：语义目标 {targets.Length} 个，移动点 {markers.Length} 个，可达 {reachableMarkers} 个，不可达 {unreachableMarkers} 个。");
            report.Add("NavMesh 区域：" + GetNavAreaSummary());
            foreach (CreatureSemanticTarget target in targets.OrderBy(target => target.targetId))
            {
                string markerIds = target.linkedMarkers == null
                    ? "无"
                    : string.Join(", ", target.linkedMarkers.Where(marker => marker != null).Select(marker => marker.id));
                Bounds bounds = CalculateBounds(target.gameObject);
                report.Add($"- {target.targetId} / {target.displayName} / {target.navigationKind} / size={bounds.size.x:0.0},{bounds.size.y:0.0},{bounds.size.z:0.0} / markers: {markerIds}");
            }

            string message = string.Join("\n", report);
            if (showDialog)
            {
                EditorUtility.DisplayDialog("场景语义可达性", message, "确定");
            }

            return message;
        }

        private static List<SemanticCandidate> CollectCandidates()
        {
            List<SemanticCandidate> candidates = new List<SemanticCandidate>();
            foreach (Renderer renderer in CreatureObjectFinder.FindObjectsByType<Renderer>(false))
            {
                if (renderer == null || renderer.gameObject == null || ShouldIgnore(renderer.gameObject))
                {
                    continue;
                }

                Bounds bounds = renderer.bounds;
                if (bounds.size.sqrMagnitude < 0.05f)
                {
                    continue;
                }

                GameObject targetObject = PickSemanticHost(renderer.gameObject);
                if (targetObject == null || ShouldIgnore(targetObject))
                {
                    continue;
                }

                Bounds hostBounds = targetObject == renderer.gameObject ? bounds : CalculateBounds(targetObject);
                float score = ScoreCandidate(targetObject.name, hostBounds);
                candidates.Add(new SemanticCandidate(targetObject, hostBounds, score));
            }

            return candidates
                .GroupBy(candidate => candidate.GameObject)
                .Select(group => group.OrderByDescending(candidate => candidate.Score).First())
                .OrderByDescending(candidate => candidate.Score)
                .ToList();
        }

        private static GameObject PickSemanticHost(GameObject source)
        {
            if (source.GetComponent<Renderer>() != null)
            {
                Transform parent = source.transform.parent;
                if (IsRendererProxyName(source.name) &&
                    parent != null &&
                    !ShouldIgnore(parent.gameObject) &&
                    !IsSceneContainerName(parent.name) &&
                    !IsGenericName(parent.name))
                {
                    return parent.gameObject;
                }

                return source;
            }

            Transform current = source.transform;
            while (current.parent != null &&
                   !ShouldIgnore(current.parent.gameObject) &&
                   current.parent.GetComponent<CreatureBrain>() == null &&
                   current.parent.GetComponent<CreatureLocationMarker>() == null)
            {
                if (current.parent.GetComponent<Renderer>() == null && current.parent.childCount > 0)
                {
                    current = current.parent;
                    continue;
                }

                break;
            }

            return current.gameObject;
        }

        private static int CleanupStaleAutoTargets(HashSet<GameObject> candidateObjects)
        {
            int removed = 0;
            CreatureSemanticTarget[] existingTargets = CreatureObjectFinder.FindObjectsByType<CreatureSemanticTarget>(true);
            foreach (CreatureSemanticTarget target in existingTargets)
            {
                if (target == null ||
                    !target.isAutoGenerated ||
                    candidateObjects.Contains(target.gameObject) ||
                    IsVirtualSemanticTarget(target))
                {
                    continue;
                }

                foreach (CreatureLocationMarker marker in CreatureObjectFinder.FindObjectsByType<CreatureLocationMarker>(true))
                {
                    if (marker == null ||
                        !marker.isSemanticGenerated ||
                        !string.Equals(marker.semanticTargetId, target.targetId, StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }

                    Undo.DestroyObjectImmediate(marker.gameObject);
                }

                Undo.DestroyObjectImmediate(target);
                removed++;
            }

            return removed;
        }

        private static int EnsureBoundaryTargets(List<SemanticCandidate> candidates, HashSet<string> usedIds, ref int markerCount)
        {
            if (candidates == null || candidates.Count == 0)
            {
                return 0;
            }

            SemanticCandidate arena = candidates
                .OrderByDescending(candidate => candidate.Bounds.size.x * candidate.Bounds.size.z)
                .First();
            Bounds bounds = arena.Bounds;
            if (bounds.size.x < 15f || bounds.size.z < 15f)
            {
                return 0;
            }

            Transform parent = FindOrCreateVirtualParent();
            float inset = Mathf.Max(2f, Mathf.Min(bounds.size.x, bounds.size.z) * 0.08f);
            BoundaryDefinition[] boundaries =
            {
                new BoundaryDefinition("wall_north", "北侧围墙/边界", new Vector3(bounds.center.x, bounds.center.y, bounds.max.z), new Vector3(bounds.center.x, bounds.center.y, bounds.max.z - inset)),
                new BoundaryDefinition("wall_south", "南侧围墙/边界", new Vector3(bounds.center.x, bounds.center.y, bounds.min.z), new Vector3(bounds.center.x, bounds.center.y, bounds.min.z + inset)),
                new BoundaryDefinition("wall_east", "东侧围墙/边界", new Vector3(bounds.max.x, bounds.center.y, bounds.center.z), new Vector3(bounds.max.x - inset, bounds.center.y, bounds.center.z)),
                new BoundaryDefinition("wall_west", "西侧围墙/边界", new Vector3(bounds.min.x, bounds.center.y, bounds.center.z), new Vector3(bounds.min.x + inset, bounds.center.y, bounds.center.z))
            };

            int touched = 0;
            foreach (BoundaryDefinition boundary in boundaries)
            {
                CreatureSemanticTarget target = FindSemanticTarget(boundary.Id);
                if (target == null)
                {
                    GameObject targetObject = new GameObject("语义目标_" + boundary.Id);
                    Undo.RegisterCreatedObjectUndo(targetObject, "创建边界语义目标");
                    targetObject.transform.SetParent(parent);
                    targetObject.transform.position = boundary.TargetPosition;
                    target = targetObject.AddComponent<CreatureSemanticTarget>();
                    touched++;
                }
                else
                {
                    Undo.RecordObject(target.transform, "更新边界语义目标");
                    target.transform.SetParent(parent);
                    target.transform.position = boundary.TargetPosition;
                }

                Undo.RecordObject(target, "配置边界语义目标");
                target.targetId = boundary.Id;
                target.displayName = boundary.DisplayName;
                target.description = "场景边界或围墙，智能体可以靠近观察，但不能把它当成可穿越目的地。";
                target.semanticTags = "blocked,wall,boundary,观察,不可穿越";
                target.navigationKind = CreatureNavigationKind.Blocked;
                target.dangerLevel = 2;
                target.interestWeight = 2;
                target.approachRadius = Mathf.Max(3f, inset);
                target.isAutoGenerated = true;
                if (target.linkedMarkers == null)
                {
                    target.linkedMarkers = new List<CreatureLocationMarker>();
                }

                markerCount += EnsureMarker(target, "viewpoint", boundary.MarkerPosition, boundary.DisplayName + " 观察点");
                usedIds.Add(boundary.Id);
                EditorUtility.SetDirty(target);
            }

            return touched;
        }

        private static Transform FindOrCreateVirtualParent()
        {
            GameObject existing = GameObject.Find("场景语义目标");
            if (existing != null)
            {
                return existing.transform;
            }

            GameObject parent = new GameObject("场景语义目标");
            Undo.RegisterCreatedObjectUndo(parent, "创建场景语义目标容器");
            return parent.transform;
        }

        private static CreatureSemanticTarget FindSemanticTarget(string targetId)
        {
            foreach (CreatureSemanticTarget target in CreatureObjectFinder.FindObjectsByType<CreatureSemanticTarget>(true))
            {
                if (target != null && string.Equals(target.targetId, targetId, StringComparison.OrdinalIgnoreCase))
                {
                    return target;
                }
            }

            return null;
        }

        private static bool IsVirtualSemanticTarget(CreatureSemanticTarget target)
        {
            return target != null &&
                   target.gameObject.name.StartsWith("语义目标_", StringComparison.Ordinal);
        }

        private static bool ShouldIgnore(GameObject gameObject)
        {
            if (gameObject == null ||
                gameObject.GetComponent<Camera>() != null ||
                gameObject.GetComponent<Light>() != null ||
                gameObject.GetComponent<CreatureBrain>() != null ||
                gameObject.GetComponent<CreatureLocationMarker>() != null ||
                gameObject.GetComponent<CreatureAgentDebugger>() != null)
            {
                return true;
            }

            string name = gameObject.name.ToLowerInvariant();
            return name.Contains("camera", StringComparison.Ordinal) ||
                   name.Contains("light", StringComparison.Ordinal) ||
                   name.Contains("navmesh", StringComparison.Ordinal) ||
                   name.Contains("runtime bootstrapper", StringComparison.Ordinal) ||
                   name.Contains("dontdestroyonload", StringComparison.Ordinal) ||
                   name.StartsWith("智能体移动点", StringComparison.Ordinal) ||
                   name.StartsWith("语义移动点", StringComparison.Ordinal) ||
                   name.StartsWith("智能体调试器", StringComparison.Ordinal);
        }

        private static void ConfigureTarget(CreatureSemanticTarget target, SemanticCandidate candidate, HashSet<string> usedIds, bool created)
        {
            Undo.RecordObject(target, "配置场景语义目标");
            CreatureNavigationKind kind = GuessKind(candidate.GameObject.name, candidate.Bounds);
            string baseId = GuessBaseId(candidate.GameObject.name, kind, candidate.Bounds);
            if (created || string.IsNullOrWhiteSpace(target.targetId))
            {
                target.targetId = UniqueId(baseId, usedIds);
                usedIds.Add(target.targetId);
            }

            target.displayName = GuessDisplayName(candidate.GameObject.name, kind);
            target.description = GuessDescription(candidate.GameObject.name, kind);
            target.semanticTags = GuessTags(candidate.GameObject.name, kind);
            target.navigationKind = kind;
            target.dangerLevel = kind == CreatureNavigationKind.Blocked ? 2 : 0;
            target.interestWeight = GuessInterestWeight(kind);
            target.approachRadius = Mathf.Max(2f, Mathf.Min(8f, candidate.Bounds.extents.magnitude + 1.5f));
            target.isAutoGenerated = true;
            EditorUtility.SetDirty(target);
        }

        private static int EnsureMarkersForTarget(CreatureSemanticTarget target, Bounds bounds)
        {
            if (target == null)
            {
                return 0;
            }

            int count = 0;
            if (target.linkedMarkers == null)
            {
                target.linkedMarkers = new List<CreatureLocationMarker>();
            }

            string suffix = target.navigationKind == CreatureNavigationKind.Blocked ? "viewpoint" :
                target.navigationKind == CreatureNavigationKind.InteractOnly ? "inspect" :
                target.navigationKind == CreatureNavigationKind.Platform ? "platform" : "base";
            count += EnsureMarker(target, suffix, bounds.center, target.displayName + " 接近点");

            if (target.navigationKind == CreatureNavigationKind.Climbable)
            {
                Vector3 top = new Vector3(bounds.center.x, bounds.max.y, bounds.center.z);
                count += EnsureMarker(target, "top", top, target.displayName + " 顶部观察点", allowUnreachable: false);
            }

            return count;
        }

        private static int EnsureMarker(CreatureSemanticTarget target, string suffix, Vector3 desiredPosition, string displayName, bool allowUnreachable = true)
        {
            string markerId = $"{target.targetId}_{suffix}";
            CreatureLocationMarker marker = FindMarker(markerId);
            bool created = false;
            if (marker == null)
            {
                Vector3 markerPosition = desiredPosition;
                if (!NavMesh.SamplePosition(desiredPosition, out NavMeshHit createHit, Mathf.Max(3f, target.approachRadius + 2f), NavMesh.AllAreas))
                {
                    if (!allowUnreachable)
                    {
                        return 0;
                    }
                }
                else
                {
                    markerPosition = createHit.position;
                }

                GameObject markerObject = new GameObject("语义移动点_" + markerId);
                Undo.RegisterCreatedObjectUndo(markerObject, "创建语义移动点");
                markerObject.transform.position = markerPosition;
                marker = markerObject.AddComponent<CreatureLocationMarker>();
                created = true;
            }
            else
            {
                Undo.RecordObject(marker, "更新语义移动点");
            }

            marker.id = markerId;
            marker.displayName = displayName;
            marker.description = $"用于接近或观察“{target.displayName}”。";
            marker.tags = target.semanticTags;
            marker.priority = Mathf.Max(1, target.interestWeight);
            marker.semanticTargetId = target.targetId;
            marker.navigationKind = target.navigationKind;
            marker.isSemanticGenerated = true;

            if (NavMesh.SamplePosition(marker.transform.position, out NavMeshHit hit, 1.5f, NavMesh.AllAreas))
            {
                marker.navAreaName = AreaMaskToName(hit.mask);
            }

            if (!target.linkedMarkers.Contains(marker))
            {
                Undo.RecordObject(target, "绑定语义移动点");
                target.linkedMarkers.Add(marker);
                EditorUtility.SetDirty(target);
            }

            EditorUtility.SetDirty(marker);
            return created ? 1 : 0;
        }

        private static CreatureLocationMarker FindMarker(string id)
        {
            foreach (CreatureLocationMarker marker in CreatureObjectFinder.FindObjectsByType<CreatureLocationMarker>(true))
            {
                if (marker != null && string.Equals(marker.id, id, StringComparison.OrdinalIgnoreCase))
                {
                    return marker;
                }
            }

            return null;
        }

        private static Bounds CalculateBounds(GameObject gameObject)
        {
            Renderer[] renderers = gameObject.GetComponentsInChildren<Renderer>();
            if (renderers.Length == 0)
            {
                return new Bounds(gameObject.transform.position, Vector3.one);
            }

            Bounds bounds = renderers[0].bounds;
            for (int i = 1; i < renderers.Length; i++)
            {
                bounds.Encapsulate(renderers[i].bounds);
            }

            return bounds;
        }

        private static float ScoreCandidate(string name, Bounds bounds)
        {
            float score = bounds.size.magnitude;
            CreatureNavigationKind kind = GuessKind(name, bounds);
            if (kind != CreatureNavigationKind.Walkable)
            {
                score += 100f;
            }

            if (!IsGenericName(name))
            {
                score += 20f;
            }

            return score;
        }

        private static CreatureNavigationKind GuessKind(string name)
        {
            return GuessKind(name, new Bounds(Vector3.zero, Vector3.one));
        }

        private static CreatureNavigationKind GuessKind(string name, Bounds bounds)
        {
            string normalized = name.ToLowerInvariant();
            if (ContainsAny(normalized, "tower", "塔", "pillar", "柱", "stairs", "stair", "楼梯", "阶梯"))
            {
                return CreatureNavigationKind.Climbable;
            }

            if (ContainsAny(normalized, "wall", "fence", "barrier", "围墙", "墙", "栅栏", "栏杆"))
            {
                return CreatureNavigationKind.Blocked;
            }

            if (ContainsAny(normalized, "platform", "bridge", "平台", "台", "桥"))
            {
                return CreatureNavigationKind.Platform;
            }

            if (ContainsAny(normalized, "jump", "跳"))
            {
                return CreatureNavigationKind.JumpArea;
            }

            if (ContainsAny(normalized, "star", "collectible", "light", "星", "灯"))
            {
                return CreatureNavigationKind.InteractOnly;
            }

            Vector3 size = bounds.size;
            float height = Mathf.Max(0.01f, size.y);
            float horizontalMax = Mathf.Max(size.x, size.z);
            float horizontalMin = Mathf.Max(0.01f, Mathf.Min(size.x, size.z));
            float footprint = Mathf.Max(0.01f, Mathf.Sqrt(Mathf.Max(0.01f, size.x * size.z)));

            if (horizontalMax > 20f && horizontalMin > 20f)
            {
                return CreatureNavigationKind.Platform;
            }

            if (height > 1.2f && horizontalMax > horizontalMin * 3.2f && horizontalMax > 3f)
            {
                return CreatureNavigationKind.Blocked;
            }

            if (height > 4f && height > footprint * 1.35f)
            {
                return CreatureNavigationKind.Climbable;
            }

            if (size.y < 1.4f && horizontalMax > 2f && horizontalMin > 1f)
            {
                return CreatureNavigationKind.Platform;
            }

            return CreatureNavigationKind.Walkable;
        }

        private static string GuessBaseId(string name, CreatureNavigationKind kind, Bounds bounds)
        {
            string semanticId = CreatureSemanticTarget.MakeId(name);
            if (IsGenericName(name))
            {
                string position = $"{Mathf.RoundToInt(bounds.center.x)}_{Mathf.RoundToInt(bounds.center.z)}";
                semanticId = kind.ToString().ToLowerInvariant() + "_" + semanticId + "_" + position;
            }

            return semanticId;
        }

        private static string UniqueId(string baseId, HashSet<string> used)
        {
            string id = string.IsNullOrWhiteSpace(baseId) ? "semantic_target" : baseId;
            int index = 2;
            while (used.Contains(id))
            {
                id = $"{baseId}_{index}";
                index++;
            }

            return id;
        }

        private static string GuessDisplayName(string name, CreatureNavigationKind kind)
        {
            string clean = CleanName(name);
            if (IsGenericName(name))
            {
                switch (kind)
                {
                    case CreatureNavigationKind.Climbable:
                        clean = "高塔/立柱 " + clean;
                        break;
                    case CreatureNavigationKind.Blocked:
                        clean = "围墙/边界 " + clean;
                        break;
                    case CreatureNavigationKind.Platform:
                        clean = "平台/地面 " + clean;
                        break;
                }
            }

            switch (kind)
            {
                case CreatureNavigationKind.Climbable:
                    return "可攀爬目标：" + clean;
                case CreatureNavigationKind.Blocked:
                    return "边界/围墙：" + clean;
                case CreatureNavigationKind.Platform:
                    return "平台：" + clean;
                case CreatureNavigationKind.InteractOnly:
                    return "可观察物体：" + clean;
                case CreatureNavigationKind.JumpArea:
                    return "跳跃区域：" + clean;
                default:
                    return clean;
            }
        }

        private static string GuessDescription(string name, CreatureNavigationKind kind)
        {
            switch (kind)
            {
                case CreatureNavigationKind.Climbable:
                    return "可能可以接近、攀爬或从高处观察的场景结构。";
                case CreatureNavigationKind.Blocked:
                    return "阻挡或围合场景的边界，适合从附近观察但不能直接穿越。";
                case CreatureNavigationKind.Platform:
                    return "可以站立、靠近或作为路径节点的平台。";
                case CreatureNavigationKind.InteractOnly:
                    return "适合观察或互动的物体，移动时应选择附近接近点。";
                case CreatureNavigationKind.JumpArea:
                    return "可能需要跳跃或特殊移动才能通过的区域。";
                default:
                    return "从场景对象名称自动生成的可探索目标。";
            }
        }

        private static string GuessTags(string name, CreatureNavigationKind kind)
        {
            string baseTag = kind.ToString().ToLowerInvariant();
            string clean = CreatureSemanticTarget.MakeId(name);
            return $"{baseTag},{clean}";
        }

        private static int GuessInterestWeight(CreatureNavigationKind kind)
        {
            switch (kind)
            {
                case CreatureNavigationKind.Climbable:
                case CreatureNavigationKind.Platform:
                    return 3;
                case CreatureNavigationKind.InteractOnly:
                case CreatureNavigationKind.JumpArea:
                    return 2;
                default:
                    return 1;
            }
        }

        private static bool ContainsAny(string value, params string[] patterns)
        {
            return patterns.Any(pattern => value.Contains(pattern, StringComparison.OrdinalIgnoreCase));
        }

        private static bool IsGenericName(string name)
        {
            string normalized = name.ToLowerInvariant();
            return normalized.StartsWith("cube", StringComparison.Ordinal) ||
                   normalized.StartsWith("sphere", StringComparison.Ordinal) ||
                   normalized.StartsWith("立方体", StringComparison.Ordinal) ||
                   normalized.StartsWith("object", StringComparison.Ordinal);
        }

        private static bool IsRendererProxyName(string name)
        {
            string normalized = name.ToLowerInvariant();
            return string.Equals(normalized, "mesh", StringComparison.Ordinal) ||
                   string.Equals(normalized, "model", StringComparison.Ordinal) ||
                   string.Equals(normalized, "geometry", StringComparison.Ordinal);
        }

        private static bool IsSceneContainerName(string name)
        {
            string normalized = name.ToLowerInvariant();
            return normalized.Contains("scene", StringComparison.Ordinal) ||
                   normalized.Contains("space", StringComparison.Ordinal) ||
                   normalized.Contains("digispace", StringComparison.Ordinal) ||
                   normalized.Contains("container", StringComparison.Ordinal);
        }

        private static string CleanName(string name)
        {
            return string.IsNullOrWhiteSpace(name)
                ? "未命名对象"
                : name.Replace("_", " ").Trim();
        }

        private static string GetNavAreaSummary()
        {
            List<string> names = new List<string>();
            for (int i = 0; i < 32; i++)
            {
                string areaName = EditorNavAreaName(i);
                if (!string.IsNullOrWhiteSpace(areaName))
                {
                    names.Add($"{i}:{areaName}");
                }
            }

            return names.Count == 0 ? "无命名区域" : string.Join(", ", names);
        }

        private static string AreaMaskToName(int mask)
        {
            for (int i = 0; i < 32; i++)
            {
                if ((mask & (1 << i)) == 0)
                {
                    continue;
                }

                string areaName = EditorNavAreaName(i);
                if (!string.IsNullOrWhiteSpace(areaName))
                {
                    return areaName;
                }
            }

            return "Unknown";
        }

        private static string EditorNavAreaName(int areaIndex)
        {
            string[] names = NavMesh.GetAreaNames();
            return areaIndex >= 0 && areaIndex < names.Length ? names[areaIndex] : string.Empty;
        }

        private readonly struct SemanticCandidate
        {
            public SemanticCandidate(GameObject gameObject, Bounds bounds, float score)
            {
                GameObject = gameObject;
                Bounds = bounds;
                Score = score;
            }

            public GameObject GameObject { get; }
            public Bounds Bounds { get; }
            public float Score { get; }
        }

        private readonly struct BoundaryDefinition
        {
            public BoundaryDefinition(string id, string displayName, Vector3 targetPosition, Vector3 markerPosition)
            {
                Id = id;
                DisplayName = displayName;
                TargetPosition = targetPosition;
                MarkerPosition = markerPosition;
            }

            public string Id { get; }
            public string DisplayName { get; }
            public Vector3 TargetPosition { get; }
            public Vector3 MarkerPosition { get; }
        }
    }
}
